pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn clean install'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'npm install'
        sh 'npm run build'
      }
    }
    stage('Database') {
      agent {
        docker { image 'mysql:latest' }
      }
      steps {
        sh 'mysql --version'
        sh 'echo "SHOW TABLES;" | mysql -u root -proot'
      }
    }
  }
}
